'use strict';

const { app, dbConnect, runServer, closeServer } = require('./index');
const { Questions } = require('./questions');

const defaultScore = 2;

const questions = [
  { brit: 'about-turn', us: 'U-turn', score: defaultScore  },
  { brit: 'accountancy', us: 'accounting', score: defaultScore  },
  { brit: 'across the pond', us: 'in America', score: defaultScore  },
  { brit: 'advert', us: 'commercial', score: defaultScore  },
  { brit: 'aerial', us: 'antenna', score: defaultScore  },
  { brit: 'aeroplane', us: 'airplane', score: defaultScore  },
  { brit: 'afters', us: 'dessert', score: defaultScore  },
  { brit: 'aga', us: 'stove', score: defaultScore  },
  { brit: 'ageing', us: 'aging', score: defaultScore  },
  { brit: 'agony aunt', us: 'advice columnist', score: defaultScore  },
  { brit: 'alcopop', us: 'Sugary ladies drink', score: defaultScore  },
  { brit: 'ale', us: 'Beer', score: defaultScore  },
  { brit: 'alreet', us: 'alright', score: defaultScore  },
  { brit: 'aluminium', us: 'aluminum', score: defaultScore  },
  { brit: 'americans killing brits', us: 'friendly fire', score: defaultScore  },
  { brit: 'amongst', us: 'Among', score: defaultScore  },
  { brit: 'amphitheatre', us: 'amphitheater', score: defaultScore  },
  { brit: 'analogue', us: 'analog', score: defaultScore  },
  { brit: 'analyse', us: 'analyze', score: defaultScore  },
  { brit: 'analysing', us: 'Analyzing', score: defaultScore  },
  { brit: 'anorak', us: 'geek', score: defaultScore  },
  { brit: 'ansafone', us: 'answering machine', score: defaultScore  },
  { brit: 'answerphone', us: 'answering machine', score: defaultScore  },
  { brit: 'anti-clockwise', us: 'counter-clockwise', score: defaultScore  },
  { brit: 'anticlockwise', us: 'counterclockwise', score: defaultScore  },
  { brit: 'anyroad', us: 'anyway', score: defaultScore  },
  { brit: 'apologise', us: 'apologize', score: defaultScore  },
  { brit: 'appetiser', us: 'appetizer', score: defaultScore  },
  { brit: 'apple and pears', us: 'stairs', score: defaultScore  },
  { brit: 'apple n pears', us: 'stairs', score: defaultScore  },
  { brit: 'apples and pears', us: 'stairs', score: defaultScore  },
  { brit: 'arguements', us: 'arguments', score: defaultScore  },
  { brit: 'aris', us: 'ass', score: defaultScore  },
  { brit: 'armour', us: 'Armor', score: defaultScore  },
  { brit: 'armoury', us: 'armory', score: defaultScore  },
  { brit: 'arse', us: 'ass', score: defaultScore  },
  { brit: 'arse over tit', us: 'Head over heels', score: defaultScore  },
  { brit: 'arsed', us: 'bothered', score: defaultScore  },
  { brit: 'arsehole', us: 'asshole', score: defaultScore  },
  { brit: 'arseholed', us: 'drunk', score: defaultScore  },
  { brit: 'aubergine', us: 'eggplant', score: defaultScore  },
  { brit: 'aubergines', us: 'eggplants', score: defaultScore  },
  { brit: 'aussie', us: 'australian', score: defaultScore  },
  { brit: 'autocue', us: 'Teleprompter', score: defaultScore  },
  { brit: 'axe wound', us: 'vagina', score: defaultScore  },
  { brit: 'aye', us: 'yeah', score: defaultScore  },
  { brit: 'aye-up', us: 'hello', score: defaultScore  },
  { brit: 'back tickler', us: 'homosexual', score: defaultScore  },
  { brit: 'badly packed kebab', us: 'vagina', score: defaultScore  },
  { brit: 'bafoon', us: 'idiot', score: defaultScore  },
  { brit: 'bagsie', us: 'claim', score: defaultScore  },
  { brit: 'bairn', us: 'child', score: defaultScore  },
  { brit: 'bairns', us: 'kids', score: defaultScore  },
  { brit: 'baltic', us: 'very cold', score: defaultScore  },
  { brit: 'bampot', us: 'clumsy idiot', score: defaultScore  },
  { brit: 'bang', us: 'fuck', score: defaultScore  },
  { brit: 'bangers', us: 'sausages', score: defaultScore  },
  { brit: 'bap', us: 'breast', score: defaultScore  },
  { brit: 'bargepole', us: 'ten-foot pole', score: defaultScore  },
  { brit: 'barking', us: 'crazy', score: defaultScore  },
  { brit: 'barm cake', us: 'bread roll', score: defaultScore  },
  { brit: 'barman', us: 'Bartender', score: defaultScore  },
  { brit: 'barmy', us: 'idiotic', score: defaultScore  },
  { brit: 'barnet', us: 'hair', score: defaultScore  },
  { brit: 'barney', us: 'trouble', score: defaultScore  },
  { brit: 'barney rubble', us: 'trouble', score: defaultScore  },
  { brit: 'barrister', us: 'lawyer', score: defaultScore  },
  { brit: 'barry', us: 'excellent', score: defaultScore  },
  { brit: 'bash on', us: 'perservere', score: defaultScore  },
  { brit: 'batty', us: 'gay', score: defaultScore  },
  { brit: 'batty man', us: 'homosexual', score: defaultScore  },
  { brit: 'bedsit', us: 'one room apartment', score: defaultScore  },
  { brit: 'beef bayonet', us: 'penis', score: defaultScore  },
  { brit: 'beef curtains', us: 'vagina', score: defaultScore  },
  { brit: 'bees and honey', us: 'Money', score: defaultScore  },
  { brit: 'behaviour', us: 'behavior', score: defaultScore  },
  { brit: 'bell end', us: 'penis tip', score: defaultScore  },
  { brit: 'bellend', us: 'dickhead', score: defaultScore  },
  { brit: 'bellow', us: 'yell', score: defaultScore  },
  { brit: 'bender', us: 'drinking session', score: defaultScore  },
  { brit: 'bendo', us: 'homosexual', score: defaultScore  },
  { brit: 'berk', us: 'idiot', score: defaultScore  },
  { brit: 'bespoke', us: 'customized', score: defaultScore  },
  { brit: 'bessy', us: 'best', score: defaultScore  },
  { brit: 'bevvie', us: 'alcoholic drink', score: defaultScore  },
  { brit: 'bevvy', us: 'alcoholic drink', score: defaultScore  },
  { brit: 'biccie', us: 'cookie', score: defaultScore  },
  { brit: 'biffa', us: 'ugly chick', score: defaultScore  },
  { brit: 'bifter', us: 'ciggarette', score: defaultScore  },
  { brit: 'bil', us: 'police', score: defaultScore  },
  { brit: 'bin bagged', us: 'evicted', score: defaultScore  },
  { brit: 'bint', us: 'woman', score: defaultScore  },
  { brit: 'biro', us: 'ball point pen', score: defaultScore  },
  { brit: 'biscuit', us: 'cookie', score: defaultScore  },
  { brit: 'biscuits', us: 'cookies', score: defaultScore  },
  { brit: 'black bag', us: 'Trash Bag', score: defaultScore  },
  { brit: 'bladdered', us: 'drunk', score: defaultScore  },
  { brit: 'blag', us: 'mooch', score: defaultScore  },
  { brit: 'blagged', us: 'robbed', score: defaultScore  },
  { brit: 'blates', us: 'blatently', score: defaultScore  },
  { brit: 'blathered', us: 'drunk', score: defaultScore  },
  { brit: 'bleedin\'', us: 'very', score: defaultScore  },
  { brit: 'blem', us: 'cigarette', score: defaultScore  },
  { brit: 'blighter', us: 'asshole', score: defaultScore  },
  { brit: 'blighty', us: 'britian', score: defaultScore  },
  { brit: 'blimey', us: 'wow', score: defaultScore  },
  { brit: 'blinding', us: 'excellent', score: defaultScore  },
  { brit: 'blinking', us: 'fucking', score: defaultScore  },
  { brit: 'bloater', us: 'fat', score: defaultScore  },
  { brit: 'bloke', us: 'guy', score: defaultScore  },
  { brit: 'bloody', us: 'fucking', score: defaultScore  },
  { brit: 'bloody nora', us: 'wow', score: defaultScore  },
  { brit: 'blooming', us: 'fucking', score: defaultScore  },
  { brit: 'blotto', us: 'drunk', score: defaultScore  },
  { brit: 'blow off', us: 'fart', score: defaultScore  },
  { brit: 'blower', us: 'telephone', score: defaultScore  },
  { brit: 'blud', us: 'brother', score: defaultScore  },
  { brit: 'boabie', us: 'penis', score: defaultScore  },
  { brit: 'bob\'s your uncle', us: 'and there you have it', score: defaultScore  },
  { brit: 'bobbie', us: 'policeman', score: defaultScore  },
  { brit: 'bobbins', us: 'rubbish', score: defaultScore  },
  { brit: 'bobby', us: 'Cop', score: defaultScore  },
  { brit: 'bodge', us: 'screw up', score: defaultScore  },
  { brit: 'bodge job', us: 'quick fix', score: defaultScore  },
  { brit: 'boff', us: 'fuck', score: defaultScore  },
  { brit: 'boffed', us: 'fucked', score: defaultScore  },
  { brit: 'boffin', us: 'nerd', score: defaultScore  },
  { brit: 'bofoon', us: 'idiot', score: defaultScore  },
  { brit: 'bog', us: 'toilet', score: defaultScore  },
  { brit: 'bog roll', us: 'toilet paper', score: defaultScore  },
  { brit: 'bog standard', us: 'basic', score: defaultScore  },
  { brit: 'boggart', us: 'bogeyman', score: defaultScore  },
  { brit: 'bogie', us: 'booger', score: defaultScore  },
  { brit: 'boink', us: 'Fuck', score: defaultScore  },
  { brit: 'bollard', us: 'metal pole', score: defaultScore  },
  { brit: 'bollocking', us: 'telling off', score: defaultScore  },
  { brit: 'bollocks', us: 'testicles', score: defaultScore  },
  { brit: 'bonk', us: 'fuck', score: defaultScore  },
  { brit: 'bonked', us: 'fucked', score: defaultScore  },
  { brit: 'bonkers', us: 'insane', score: defaultScore  },
  { brit: 'bonnet', us: 'hood', score: defaultScore  },
  { brit: 'boobarse', us: 'cunt', score: defaultScore  },
  { brit: 'bootnote', us: 'footnote', score: defaultScore  },
  { brit: 'boozer', us: 'bar', score: defaultScore  },
  { brit: 'borstal', us: 'juvenile detention center', score: defaultScore  },
  { brit: 'bounder', us: 'bad egg', score: defaultScore  },
  { brit: 'bovad', us: 'bothered', score: defaultScore  },
  { brit: 'boxing day', us: 'day after christmas', score: defaultScore  },
  { brit: 'brass', us: 'money', score: defaultScore  },
  { brit: 'brass flute', us: 'prostitute', score: defaultScore  },
  { brit: 'brass monkeys', us: 'cold', score: defaultScore  },
  { brit: 'brill', us: 'brilliant', score: defaultScore  },
  { brit: 'bristols', us: 'breasts', score: defaultScore  },
  { brit: 'brolly', us: 'umbrella', score: defaultScore  },
  { brit: 'brown bread', us: 'Dead', score: defaultScore  },
  { brit: 'brub', us: 'Brother', score: defaultScore  },
  { brit: 'brum', us: 'Birmingham', score: defaultScore  },
  { brit: 'brummie', us: 'a person from Birmingham', score: defaultScore  },
  { brit: 'brush', us: 'broom', score: defaultScore  },
  { brit: 'bubtion', us: 'baby', score: defaultScore  },
  { brit: 'bugbear', us: 'bogeyman', score: defaultScore  },
  { brit: 'bugger', us: 'asshole', score: defaultScore  },
  { brit: 'bugger', us: 'asshole', score: defaultScore  },
  { brit: 'bullocks', us: 'Testicles', score: defaultScore  },
  { brit: 'bullocksae', us: 'bullshit', score: defaultScore  },
  { brit: 'bum', us: 'butt', score: defaultScore  },
  { brit: 'bum bag', us: 'fanny pack', score: defaultScore  },
  { brit: 'bumbershoot', us: 'umbrella', score: defaultScore  },
  { brit: 'bumf', us: 'paperwork', score: defaultScore  },
  { brit: 'bunch of fives', us: 'fist', score: defaultScore  },
  { brit: 'bung', us: 'throw', score: defaultScore  },
  { brit: 'busk', us: 'play music in the street', score: defaultScore  },
  { brit: 'busker', us: 'street musician', score: defaultScore  },
  { brit: 'busking', us: 'Playing music for tips', score: defaultScore  },
  { brit: 'butcher\'s', us: 'look', score: defaultScore  },
  { brit: 'butcher\'s hook', us: 'look', score: defaultScore  },
  { brit: 'butchers', us: 'look', score: defaultScore  },
  { brit: 'butters', us: 'Ugly', score: defaultScore  },
  { brit: 'buttie', us: 'sandwich', score: defaultScore  },
  { brit: 'butty bar', us: 'sandwich shop', score: defaultScore  },
  { brit: 'cack', us: 'shit', score: defaultScore  },
  { brit: 'cackhanded', us: 'clumsy', score: defaultScore  },
  { brit: 'caffler', us: 'idiot', score: defaultScore  },
  { brit: 'cakehole', us: 'mouth', score: defaultScore  },
  { brit: 'calibre', us: 'caliber', score: defaultScore  },
  { brit: 'camp', us: 'homosexual', score: defaultScore  },
  { brit: 'candy floss', us: 'cotton candy', score: defaultScore  },
  { brit: 'candyfloss', us: 'cottoncandy', score: defaultScore  },
  { brit: 'caned', us: 'stoned', score: defaultScore  },
  { brit: 'capitalise', us: 'capitalize', score: defaultScore  },
  { brit: 'car boot', us: 'trunk', score: defaultScore  },
  { brit: 'car park', us: 'parking lot', score: defaultScore  },
  { brit: 'car parks', us: 'parking lots', score: defaultScore  },
  { brit: 'caravan', us: 'trailer', score: defaultScore  },
  { brit: 'careworn', us: 'looking worried', score: defaultScore  },
  { brit: 'carivan', us: 'Car', score: defaultScore  },
  { brit: 'carriageway', us: 'highway', score: defaultScore  },
  { brit: 'carrier bag', us: 'shopping bag', score: defaultScore  },
  { brit: 'cashpoint machine', us: 'ATM', score: defaultScore  },
  { brit: 'catalogue', us: 'Catalog', score: defaultScore  },
  { brit: 'cellotape', us: 'scotch tape', score: defaultScore  },
  { brit: 'centimetre', us: 'centimeter', score: defaultScore  },
  { brit: 'central reservation', us: 'median', score: defaultScore  },
  { brit: 'centre', us: 'center', score: defaultScore  },
  { brit: 'chabbie', us: 'Young child', score: defaultScore  },
  { brit: 'chabbies', us: 'Young children', score: defaultScore  },
  { brit: 'chancer', us: 'gambler', score: defaultScore  },
  { brit: 'chap', us: 'guy', score: defaultScore  },
  { brit: 'chaps', us: 'guys', score: defaultScore  },
  { brit: 'charva', us: 'white trash', score: defaultScore  },
  { brit: 'chav', us: 'White Trash wanna-be gangster', score: defaultScore  },
  { brit: 'chaved', us: 'stole', score: defaultScore  },
  { brit: 'chebs', us: 'boobs', score: defaultScore  },
  { brit: 'cheeky', us: 'rude', score: defaultScore  },
  { brit: 'cheerio', us: 'goodbye', score: defaultScore  },
  { brit: 'cheers', us: 'thank you', score: defaultScore  },
  { brit: 'cheesed off', us: 'annoyed', score: defaultScore  },
  { brit: 'cheesy', us: 'tacky', score: defaultScore  },
  { brit: 'chemist', us: 'pharmacy', score: defaultScore  },
  { brit: 'cheque', us: 'check', score: defaultScore  },
  { brit: 'cherry stone', us: 'cherry pit', score: defaultScore  },
  { brit: 'chevy chase', us: 'face', score: defaultScore  },
  { brit: 'chimminny', us: 'chimney', score: defaultScore  },
  { brit: 'china plate', us: 'friend', score: defaultScore  },
  { brit: 'chinstrapped', us: 'Very Very Tired', score: defaultScore  },
  { brit: 'chipon', us: 'pal', score: defaultScore  },
  { brit: 'chippie', us: 'restaurant', score: defaultScore  },
  { brit: 'chippy', us: 'fish and chips', score: defaultScore  },
  { brit: 'chips', us: 'fries', score: defaultScore  },
  { brit: 'chivvey', us: 'hurry', score: defaultScore  },
  { brit: 'chivvy', us: 'hurry', score: defaultScore  },
  { brit: 'chivy', us: 'Hurry', score: defaultScore  },
  { brit: 'chock a block', us: 'closely packed together', score: defaultScore  },
  { brit: 'chocolate drops', us: 'chocolate chips', score: defaultScore  },
  { brit: 'chuff', us: 'fart', score: defaultScore  },
  { brit: 'chuffed', us: 'happy', score: defaultScore  },
  { brit: 'cider', us: 'alcoholic drink', score: defaultScore  },
  { brit: 'ciggie', us: 'cigarette', score: defaultScore  },
  { brit: 'cinema', us: 'theater', score: defaultScore  },
  { brit: 'clingfilm', us: 'Saran wrap', score: defaultScore  },
  { brit: 'clobber', us: 'clothing', score: defaultScore  },
  { brit: 'clot', us: 'idiot', score: defaultScore  },
  { brit: 'clothes peg', us: 'Clothes Pin', score: defaultScore  },
  { brit: 'clumpy dumplet', us: 'short person', score: defaultScore  },
  { brit: 'cob', us: 'bun', score: defaultScore  },
  { brit: 'cobblers', us: 'nonsense', score: defaultScore  },
  { brit: 'cock', us: 'friend', score: defaultScore  },
  { brit: 'cock up', us: 'mess up', score: defaultScore  },
  { brit: 'cock-a-hoop', us: 'excited', score: defaultScore  },
  { brit: 'cockney', us: 'east londoner', score: defaultScore  },
  { brit: 'cocksure', us: 'confident', score: defaultScore  },
  { brit: 'codger', us: 'old man', score: defaultScore  },
  { brit: 'codswallop', us: 'nonsense', score: defaultScore  },
  { brit: 'coffin dodger', us: 'Old Person', score: defaultScore  },
  { brit: 'collywobbles', us: 'fear', score: defaultScore  },
  { brit: 'colonies', us: 'America', score: defaultScore  },
  { brit: 'colour', us: 'color', score: defaultScore  },
  { brit: 'come a cropper', us: 'have an accident', score: defaultScore  },
  { brit: 'come to that', us: 'for that matter', score: defaultScore  },
  { brit: 'compere', us: 'emcee', score: defaultScore  },
  { brit: 'conk', us: 'nose', score: defaultScore  },
  { brit: 'cooker', us: 'oven', score: defaultScore  },
  { brit: 'cop a', us: 'take a', score: defaultScore  },
  { brit: 'cop off', us: 'fuck', score: defaultScore  },
  { brit: 'copped off', us: 'fucked', score: defaultScore  },
  { brit: 'copper', us: 'policeman', score: defaultScore  },
  { brit: 'corking', us: 'excellent', score: defaultScore  },
  { brit: 'cornflour', us: 'cornstarch', score: defaultScore  },
  { brit: 'corridor', us: 'hallway', score: defaultScore  },
  { brit: 'costermonger', us: 'street vendor', score: defaultScore  },
  { brit: 'cosy', us: 'cozy', score: defaultScore  },
  { brit: 'cot', us: 'crib', score: defaultScore  },
  { brit: 'cotch', us: 'loiter', score: defaultScore  },
  { brit: 'cotton buds', us: 'Q-Tips', score: defaultScore  },
  { brit: 'cotton wool', us: 'cotton ball', score: defaultScore  },
  { brit: 'council house', us: 'public housing', score: defaultScore  },
  { brit: 'counsellor', us: 'counselor', score: defaultScore  },
  { brit: 'courgette', us: 'zucchini', score: defaultScore  },
  { brit: 'courgettes', us: 'zucchini', score: defaultScore  },
  { brit: 'cream crackered', us: 'tired', score: defaultScore  },
  { brit: 'creps', us: 'Sneakers', score: defaultScore  },
  { brit: 'crikey', us: 'wow', score: defaultScore  },
  { brit: 'crisp', us: 'chip', score: defaultScore  },
  { brit: 'crisps', us: 'chips', score: defaultScore  },
  { brit: 'crumbs', us: 'aw man', score: defaultScore  },
  { brit: 'crumpet', us: 'teacake', score: defaultScore  },
  { brit: 'cushy', us: 'easy', score: defaultScore  },
  { brit: 'CV', us: 'resume', score: defaultScore  },
  { brit: 'da', us: 'father', score: defaultScore  },
  { brit: 'dae', us: 'do', score: defaultScore  },
  { brit: 'daffy', us: 'silly', score: defaultScore  },
  { brit: 'daft', us: 'absent minded', score: defaultScore  },
  { brit: 'dago', us: 'spaniard', score: defaultScore  },
  { brit: 'dear', us: 'expensive', score: defaultScore  },
  { brit: 'dialogue', us: 'dialog', score: defaultScore  },
  { brit: 'diarrhoea', us: 'diarrhea', score: defaultScore  },
  { brit: 'dickey bird', us: 'word', score: defaultScore  },
  { brit: 'diddle', us: 'swindle', score: defaultScore  },
  { brit: 'dinges', us: 'underwear', score: defaultScore  },
  { brit: 'dingy', us: 'dirty', score: defaultScore  },
  { brit: 'dinnae', us: 'didn\'t', score: defaultScore  },
  { brit: 'dinner', us: 'lunch', score: defaultScore  },
  { brit: 'dishy', us: 'attractive', score: defaultScore  },
  { brit: 'dither', us: 'delay', score: defaultScore  },
  { brit: 'doddle', us: 'easy', score: defaultScore  },
  { brit: 'dodgem', us: 'bumper car', score: defaultScore  },
  { brit: 'dodgem cars', us: 'Bumper cars', score: defaultScore  },
  { brit: 'dodgy', us: 'shady', score: defaultScore  },
  { brit: 'dog & bone', us: 'Telephone', score: defaultScore  },
  { brit: 'dog and bone', us: 'phone', score: defaultScore  },
  { brit: 'dog\'s bollocks', us: 'most excellent', score: defaultScore  },
  { brit: 'dog\'s breakfast', us: 'mess', score: defaultScore  },
  { brit: 'dog-end', us: 'cigarette butt', score: defaultScore  },
  { brit: 'dogs bollocks', us: 'best', score: defaultScore  },
  { brit: 'dogsbody', us: 'servant', score: defaultScore  },
  { brit: 'dolt', us: 'idiot', score: defaultScore  },
  { brit: 'dooze', us: 'Enough', score: defaultScore  },
  { brit: 'dosh', us: 'money', score: defaultScore  },
  { brit: 'doss', us: 'sit around doing nothing', score: defaultScore  },
  { brit: 'dossing', us: 'sitting around doing nothing', score: defaultScore  },
  { brit: 'doughnut', us: 'donut', score: defaultScore  },
  { brit: 'dowdy', us: 'dull', score: defaultScore  },
  { brit: 'dozy', us: 'slow', score: defaultScore  },
  { brit: 'drailings', us: 'Teeth', score: defaultScore  },
  { brit: 'draught', us: 'draft', score: defaultScore  },
  { brit: 'draughts', us: 'checkers', score: defaultScore  },
  { brit: 'drawing pin', us: 'thumb tack', score: defaultScore  },
  { brit: 'dressing gown', us: 'bathrobe', score: defaultScore  },
  { brit: 'dual carriageway', us: 'divided highway', score: defaultScore  },
  { brit: 'dumbarse', us: 'dumbass', score: defaultScore  },
  { brit: 'dunno', us: 'dont know', score: defaultScore  },
  { brit: 'durex', us: 'condom', score: defaultScore  },
  { brit: 'dust bin', us: 'garbage can', score: defaultScore  },
  { brit: 'dust-bin-trolley', us: 'trash-truck', score: defaultScore  },
  { brit: 'dustbin', us: 'trashcan', score: defaultScore  },
  { brit: 'dustman', us: 'garbage man', score: defaultScore  },
  { brit: 'duvet', us: 'comforter', score: defaultScore  },
  { brit: 'dux', us: 'valedictorian', score: defaultScore  },
  { brit: 'dyke', us: 'lesbian', score: defaultScore  },
  { brit: 'ecosse', us: 'scotland', score: defaultScore  },
  { brit: 'eejit', us: 'idiot', score: defaultScore  },
  { brit: 'effing', us: 'fucking', score: defaultScore  },
  { brit: 'effing and blinding', us: 'swearing', score: defaultScore  },
  { brit: 'elastoplast', us: 'bandaid', score: defaultScore  },
  { brit: 'elevenses', us: 'mid morning snack', score: defaultScore  },
  { brit: 'ello', us: 'hello', score: defaultScore  },
  { brit: 'em', us: 'them', score: defaultScore  },
  { brit: 'encyclopaedia', us: 'encyclopedia', score: defaultScore  },
  { brit: 'endeavour', us: 'endeavor', score: defaultScore  },
  { brit: 'engerland', us: 'England', score: defaultScore  },
  { brit: 'estate agent', us: 'realtor', score: defaultScore  },
  { brit: 'fackin\' ell', us: 'fucking hell', score: defaultScore  },
  { brit: 'faff', us: 'pussyfoot', score: defaultScore  },
  { brit: 'fag', us: 'cigarette', score: defaultScore  },
  { brit: 'faggot', us: 'meatball', score: defaultScore  },
  { brit: 'fags', us: 'cigarettes', score: defaultScore  },
  { brit: 'fair dinkum', us: 'To be Fair', score: defaultScore  },
  { brit: 'fak', us: 'fuck', score: defaultScore  },
  { brit: 'fancies', us: 'likes', score: defaultScore  },
  { brit: 'fancy', us: 'like', score: defaultScore  },
  { brit: 'fancy dress', us: 'Costume', score: defaultScore  },
  { brit: 'fannt', us: 'vagina', score: defaultScore  },
  { brit: 'fanny', us: 'ass', score: defaultScore  },
  { brit: 'fanny flaps', us: 'pussy', score: defaultScore  },
  { brit: 'favour', us: 'favor', score: defaultScore  },
  { brit: 'favourite', us: 'favorite', score: defaultScore  },
  { brit: 'feck', us: 'fuck', score: defaultScore  },
  { brit: 'fecking', us: 'silly', score: defaultScore  },
  { brit: 'fibre', us: 'fiber', score: defaultScore  },
  { brit: 'fillet', us: 'filet', score: defaultScore  },
  { brit: 'film', us: 'movie', score: defaultScore  },
  { brit: 'fish fingers', us: 'fish sticks', score: defaultScore  },
  { brit: 'fit', us: 'Lovely', score: defaultScore  },
  { brit: 'fitty', us: 'attractive', score: defaultScore  },
  { brit: 'fizzy drink', us: 'soda', score: defaultScore  },
  { brit: 'flange', us: 'pussy', score: defaultScore  },
  { brit: 'flapp', us: 'flustered', score: defaultScore  },
  { brit: 'flatmate', us: 'roomate', score: defaultScore  },
  { brit: 'flavour', us: 'flavor', score: defaultScore  },
  { brit: 'floater', us: 'turd', score: defaultScore  },
  { brit: 'flog', us: 'sell', score: defaultScore  },
  { brit: 'floop', us: 'cock', score: defaultScore  },
  { brit: 'fluke', us: 'lucky win', score: defaultScore  },
  { brit: 'flumoxed', us: 'confused', score: defaultScore  },
  { brit: 'flutter', us: 'gamble', score: defaultScore  },
  { brit: 'flyover', us: 'overpass', score: defaultScore  },
  { brit: 'foetus', us: 'fetus', score: defaultScore  },
  { brit: 'fokked', us: 'very drunk', score: defaultScore  },
  { brit: 'fondleslab', us: 'tablet', score: defaultScore  },
  { brit: 'fondleslabs', us: 'tablets', score: defaultScore  },
  { brit: 'football', us: 'soccer', score: defaultScore  },
  { brit: 'footballer', us: 'soccer player', score: defaultScore  },
  { brit: 'footpath', us: 'sidewalk', score: defaultScore  },
  { brit: 'forenoon', us: 'morning', score: defaultScore  },
  { brit: 'fortnight', us: 'two weeks', score: defaultScore  },
  { brit: 'fringe', us: 'bangs', score: defaultScore  },
  { brit: 'frock', us: 'dress', score: defaultScore  },
  { brit: 'frog', us: 'frenchman', score: defaultScore  },
  { brit: 'fud', us: 'vagina', score: defaultScore  },
  { brit: 'full stop', us: 'period', score: defaultScore  },
  { brit: 'fuzz', us: 'police', score: defaultScore  },
  { brit: 'gaff', us: 'place', score: defaultScore  },
  { brit: 'gaffe', us: 'home', score: defaultScore  },
  { brit: 'gaffer', us: 'foreman', score: defaultScore  },
  { brit: 'gallus', us: 'Excellent', score: defaultScore  },
  { brit: 'gander', us: 'look', score: defaultScore  },
  { brit: 'gaol', us: 'jail', score: defaultScore  },
  { brit: 'gday', us: 'good day', score: defaultScore  },
  { brit: 'gear lever', us: 'stick shift', score: defaultScore  },
  { brit: 'gearbox', us: 'transmission', score: defaultScore  },
  { brit: 'geezer', us: 'dude', score: defaultScore  },
  { brit: 'geezer bird', us: 'transvestite', score: defaultScore  },
  { brit: 'geordie', us: 'person from newcastle', score: defaultScore  },
  { brit: 'george bush', us: 'Complete idiot', score: defaultScore  },
  { brit: 'gerry', us: 'german', score: defaultScore  },
  { brit: 'get my goat up', us: 'annoy me', score: defaultScore  },
  { brit: 'get to fuck!', us: 'I do not believe that to be true, Sir!', score: defaultScore  },
  { brit: 'get your bread dipped', us: 'get stuck in', score: defaultScore  },
  { brit: 'giddy', us: 'dizzy', score: defaultScore  },
  { brit: 'gimp', us: 'Disabled Person', score: defaultScore  },
  { brit: 'git', us: 'bastard', score: defaultScore  },
  { brit: 'give over', us: 'give me a break', score: defaultScore  },
  { brit: 'give way', us: 'yeild', score: defaultScore  },
  { brit: 'glaikit', us: 'stupid', score: defaultScore  },
  { brit: 'glamour', us: 'glamor', score: defaultScore  },
  { brit: 'gob', us: 'mouth', score: defaultScore  },
  { brit: 'gobbing', us: 'spitting', score: defaultScore  },
  { brit: 'gobshite', us: 'bullshit', score: defaultScore  },
  { brit: 'gobsmacked', us: 'surprised', score: defaultScore  },
  { brit: 'goggle box', us: 'TV', score: defaultScore  },
  { brit: 'googly', us: 'bouncing cricket ball', score: defaultScore  },
  { brit: 'goolies', us: 'balls', score: defaultScore  },
  { brit: 'gorgey', us: 'gorgeous', score: defaultScore  },
  { brit: 'gormless', us: 'dumb', score: defaultScore  },
  { brit: 'graft', us: 'work', score: defaultScore  },
  { brit: 'gramme', us: 'gram', score: defaultScore  },
  { brit: 'grandmummy', us: 'grandmother', score: defaultScore  },
  { brit: 'greens', us: 'vegetables', score: defaultScore  },
  { brit: 'grey', us: 'gray', score: defaultScore  },
  { brit: 'grizzle', us: 'moan', score: defaultScore  },
  { brit: 'grotty', us: 'disgusting', score: defaultScore  },
  { brit: 'ground floor', us: 'first floor', score: defaultScore  },
  { brit: 'growler', us: 'cab', score: defaultScore  },
  { brit: 'guff', us: 'fart', score: defaultScore  },
  { brit: 'guffawed', us: 'laughed', score: defaultScore  },
  { brit: 'gutted', us: 'dissapointed', score: defaultScore  },
  { brit: 'guvnor', us: 'boss', score: defaultScore  },
  { brit: 'gyp', us: 'pain', score: defaultScore  },
  { brit: 'gypo', us: 'slob', score: defaultScore  },
  { brit: 'haddaway and shite', us: 'I do not believe you, sir!', score: defaultScore  },
  { brit: 'hae', us: 'have', score: defaultScore  },
  { brit: 'hair slide', us: 'barrette', score: defaultScore  },
  { brit: 'hairy axe wound', us: 'vagina', score: defaultScore  },
  { brit: 'half inched', us: 'stolen', score: defaultScore  },
  { brit: 'hallowe\'en', us: 'halloween', score: defaultScore  },
  { brit: 'hammered', us: 'drunk', score: defaultScore  },
  { brit: 'hampstead heath', us: 'teeth', score: defaultScore  },
  { brit: 'hand luggage', us: 'carry on baggage', score: defaultScore  },
  { brit: 'handbag', us: 'Purse', score: defaultScore  },
  { brit: 'handbrake', us: 'parking brake', score: defaultScore  },
  { brit: 'harbour', us: 'harbor', score: defaultScore  },
  { brit: 'harry potter and the philosopher\'s stone', us: 'Harry Potter and the Sorceror\'s Stone', score: defaultScore  },
  { brit: 'have off', us: 'steal', score: defaultScore  },
  { brit: 'haver', us: 'ramble incoherently', score: defaultScore  },
  { brit: 'having kittens', us: 'being nervous', score: defaultScore  },
  { brit: 'haway', us: 'come along', score: defaultScore  },
  { brit: 'head boy', us: 'valedictorian', score: defaultScore  },
  { brit: 'headmaster', us: 'Principal', score: defaultScore  },
  { brit: 'hen night', us: 'bachelorette party', score: defaultScore  },
  { brit: 'her indoors', us: 'wife', score: defaultScore  },
  { brit: 'hereaboot', us: 'around here', score: defaultScore  },
  { brit: 'higgledy piggledy', us: 'jumbled up', score: defaultScore  },
  { brit: 'high flier', us: 'important person', score: defaultScore  },
  { brit: 'high street', us: 'main street', score: defaultScore  },
  { brit: 'hill walking', us: 'hiking', score: defaultScore  },
  { brit: 'hippocrockapig', us: 'ugly woman', score: defaultScore  },
  { brit: 'hire', us: 'rent', score: defaultScore  },
  { brit: 'hob', us: 'stove', score: defaultScore  },
  { brit: 'hobknocker', us: 'Idiot', score: defaultScore  },
  { brit: 'hobnocker', us: 'idiot', score: defaultScore  },
  { brit: 'homely', us: 'pleasant and comfortable', score: defaultScore  },
  { brit: 'honour', us: 'honor', score: defaultScore  },
  { brit: 'hoover', us: 'vacuum cleaner', score: defaultScore  },
  { brit: 'hoovered', us: 'vacuumed', score: defaultScore  },
  { brit: 'housemate', us: 'roommate', score: defaultScore  },
  { brit: 'how are you', us: 'how do you do', score: defaultScore  },
  { brit: 'humour', us: 'humor', score: defaultScore  },
  { brit: 'hypermarket', us: 'Supermarket', score: defaultScore  },
  { brit: 'i-tie', us: 'Italian', score: defaultScore  },
  { brit: 'ice lolly', us: 'popsicle', score: defaultScore  },
  { brit: 'icing', us: 'frosting', score: defaultScore  },
  { brit: 'ickle', us: 'very small', score: defaultScore  },
  { brit: 'in a hump', us: 'depressed', score: defaultScore  },
  { brit: 'in the shit', us: 'in trouble', score: defaultScore  },
  { brit: 'inbuilt', us: 'built-in', score: defaultScore  },
  { brit: 'init', us: 'isn\'t it', score: defaultScore  },
  { brit: 'initialise', us: 'initialize', score: defaultScore  },
  { brit: 'innit', us: 'isn\'t it', score: defaultScore  },
  { brit: 'ironmonger', us: 'hardware store', score: defaultScore  },
  { brit: 'itie', us: 'italin', score: defaultScore  },
  { brit: 'jacket potato', us: 'baked potato', score: defaultScore  },
  { brit: 'jacksie', us: 'Ass', score: defaultScore  },
  { brit: 'jam', us: 'jelly', score: defaultScore  },
  { brit: 'jam-jar', us: 'Car', score: defaultScore  },
  { brit: 'james blunt', us: 'cunt', score: defaultScore  },
  { brit: 'james hunt', us: 'cunt', score: defaultScore  },
  { brit: 'jammy', us: 'lucky', score: defaultScore  },
  { brit: 'jangle', us: 'gossip', score: defaultScore  },
  { brit: 'japs eye', us: 'pee hole', score: defaultScore  },
  { brit: 'jelly', us: 'jell-o', score: defaultScore  },
  { brit: 'jiffy', us: 'hurry', score: defaultScore  },
  { brit: 'jim-jams', us: 'Undergarments', score: defaultScore  },
  { brit: 'jings', us: 'gosh', score: defaultScore  },
  { brit: 'john thomas', us: 'penis', score: defaultScore  },
  { brit: 'johnny', us: 'Condom', score: defaultScore  },
  { brit: 'jolly wacker', us: 'Penis', score: defaultScore  },
  { brit: 'jomblies', us: 'tits', score: defaultScore  },
  { brit: 'jugs', us: 'breasts', score: defaultScore  },
  { brit: 'juiced up', us: 'drunk', score: defaultScore  },
  { brit: 'jumble sale', us: 'rummage sale', score: defaultScore  },
  { brit: 'jump leads', us: 'jumper cables', score: defaultScore  },
  { brit: 'jumper', us: 'sweater', score: defaultScore  },
  { brit: 'kagoul', us: 'poncho', score: defaultScore  },
  { brit: 'kecks', us: 'pants', score: defaultScore  },
  { brit: 'kerb', us: 'curb', score: defaultScore  },
  { brit: 'kerfuffle', us: 'big fuss', score: defaultScore  },
  { brit: 'khasi', us: 'toilet', score: defaultScore  },
  { brit: 'khyber', us: 'butt', score: defaultScore  },
  { brit: 'kilogramme', us: 'kilogram', score: defaultScore  },
  { brit: 'kilometre', us: 'kilometer', score: defaultScore  },
  { brit: 'kip', us: 'sleep', score: defaultScore  },
  { brit: 'kit', us: 'uniform', score: defaultScore  },
  { brit: 'kitchen roll', us: 'paper towel', score: defaultScore  },
  { brit: 'kiwi', us: 'new zealander', score: defaultScore  },
  { brit: 'klaxon', us: 'idiot', score: defaultScore  },
  { brit: 'knackered', us: 'tired', score: defaultScore  },
  { brit: 'knees up', us: 'party', score: defaultScore  },
  { brit: 'knicked', us: 'stole', score: defaultScore  },
  { brit: 'knickers', us: 'underwear', score: defaultScore  },
  { brit: 'knob', us: 'penis', score: defaultScore  },
  { brit: 'knobbed', us: 'fucked', score: defaultScore  },
  { brit: 'knobish', us: 'dickhead', score: defaultScore  },
  { brit: 'knock me up', us: 'bang on my door', score: defaultScore  },
  { brit: 'knock up', us: 'Wake Up', score: defaultScore  },
  { brit: 'knockers', us: 'breasts', score: defaultScore  },
  { brit: 'kraut', us: 'german', score: defaultScore  },
  { brit: 'labour', us: 'labor', score: defaultScore  },
  { brit: 'lad', us: 'guy', score: defaultScore  },
  { brit: 'laddie', us: 'boy', score: defaultScore  },
  { brit: 'laddy', us: 'boy', score: defaultScore  },
  { brit: 'ladette', us: 'lush', score: defaultScore  },
  { brit: 'lads', us: 'children', score: defaultScore  },
  { brit: 'ladybird', us: 'ladybug', score: defaultScore  },
  { brit: 'lager', us: 'pale ale', score: defaultScore  },
  { brit: 'lairy', us: 'abusive', score: defaultScore  },
  { brit: 'lashed', us: 'drunk', score: defaultScore  },
  { brit: 'lass', us: 'girl', score: defaultScore  },
  { brit: 'lassie', us: 'girl', score: defaultScore  },
  { brit: 'laughing gear', us: 'teeth', score: defaultScore  },
  { brit: 'launderette', us: 'laundromat', score: defaultScore  },
  { brit: 'lavatory', us: 'Restroom', score: defaultScore  },
  { brit: 'lavvie', us: 'restroom', score: defaultScore  },
  { brit: 'lavvy', us: 'Toilet', score: defaultScore  },
  { brit: 'lay by', us: 'rest stop', score: defaultScore  },
  { brit: 'learnt', us: 'learned', score: defaultScore  },
  { brit: 'leathered', us: 'Drunk', score: defaultScore  },
  { brit: 'leg over', us: 'sex', score: defaultScore  },
  { brit: 'lickalotapuss', us: 'lesbian', score: defaultScore  },
  { brit: 'litre', us: 'liter', score: defaultScore  },
  { brit: 'lob', us: 'Throw', score: defaultScore  },
  { brit: 'lodger', us: 'renter', score: defaultScore  },
  { brit: 'lolly', us: 'money', score: defaultScore  },
  { brit: 'lollyice', us: 'popcicle', score: defaultScore  },
  { brit: 'loo', us: 'bathroom', score: defaultScore  },
  { brit: 'lorrie', us: 'truck', score: defaultScore  },
  { brit: 'lorries', us: 'trucks', score: defaultScore  },
  { brit: 'lorry', us: 'truck', score: defaultScore  },
  { brit: 'lugholes', us: 'ears', score: defaultScore  },
  { brit: 'lurgy', us: 'sickness', score: defaultScore  },
  { brit: 'luvvie', us: 'gay actor', score: defaultScore  },
  { brit: 'ma', us: 'mom', score: defaultScore  },
  { brit: 'macintosh', us: 'raincoat', score: defaultScore  },
  { brit: 'mackintosh', us: 'raincoat', score: defaultScore  },
  { brit: 'made redundant', us: 'laid off', score: defaultScore  },
  { brit: 'mafted', us: 'hot', score: defaultScore  },
  { brit: 'make like shepherds', us: 'get the flock out of here', score: defaultScore  },
  { brit: 'manky', us: 'gross', score: defaultScore  },
  { brit: 'mardy', us: 'Moody', score: defaultScore  },
  { brit: 'massai', us: 'Fantastic', score: defaultScore  },
  { brit: 'mate', us: 'friend', score: defaultScore  },
  { brit: 'mater', us: 'mother', score: defaultScore  },
  { brit: 'mates', us: 'Friends', score: defaultScore  },
  { brit: 'maths', us: 'math', score: defaultScore  },
  { brit: 'merchant banker', us: 'wanker', score: defaultScore  },
  { brit: 'metre', us: 'meter', score: defaultScore  },
  { brit: 'mick', us: 'irishman', score: defaultScore  },
  { brit: 'miffed', us: 'upset', score: defaultScore  },
  { brit: 'mince', us: 'ground beef', score: defaultScore  },
  { brit: 'mincer', us: 'meat grinder', score: defaultScore  },
  { brit: 'ming', us: 'gross', score: defaultScore  },
  { brit: 'minge', us: 'vagina', score: defaultScore  },
  { brit: 'minged', us: 'moved in an ugly fashion', score: defaultScore  },
  { brit: 'minger', us: 'ugly', score: defaultScore  },
  { brit: 'minging', us: 'ugly as sin', score: defaultScore  },
  { brit: 'mint', us: 'good', score: defaultScore  },
  { brit: 'missus', us: 'wife', score: defaultScore  },
  { brit: 'mits', us: 'hands', score: defaultScore  },
  { brit: 'mockney', us: 'Fake London slang', score: defaultScore  },
  { brit: 'moggy', us: 'cat', score: defaultScore  },
  { brit: 'mole grip', us: 'vice', score: defaultScore  },
  { brit: 'mong', us: 'stupid person', score: defaultScore  },
  { brit: 'moose', us: 'unattractive woman', score: defaultScore  },
  { brit: 'moreover', us: 'besides', score: defaultScore  },
  { brit: 'moribund vacuity', us: 'American way', score: defaultScore  },
  { brit: 'mosey', us: 'walk', score: defaultScore  },
  { brit: 'mosie', us: 'mosquito', score: defaultScore  },
  { brit: 'motorbike', us: 'motorcycle', score: defaultScore  },
  { brit: 'motorcar', us: 'automobile', score: defaultScore  },
  { brit: 'motorway', us: 'highway', score: defaultScore  },
  { brit: 'mould', us: 'mold', score: defaultScore  },
  { brit: 'moulting', us: 'Shedding', score: defaultScore  },
  { brit: 'moustache', us: 'mustache', score: defaultScore  },
  { brit: 'mucca', us: 'Mate', score: defaultScore  },
  { brit: 'muck', us: 'dirt', score: defaultScore  },
  { brit: 'muck about', us: 'mess around', score: defaultScore  },
  { brit: 'muck raking', us: 'digging dirt', score: defaultScore  },
  { brit: 'mucker', us: 'pal', score: defaultScore  },
  { brit: 'muggle', us: 'non magic folk', score: defaultScore  },
  { brit: 'mullered', us: 'drunk', score: defaultScore  },
  { brit: 'mum', us: 'mom', score: defaultScore  },
  { brit: 'munted', us: 'drunk', score: defaultScore  },
  { brit: 'munter', us: 'unattractive woman', score: defaultScore  },
  { brit: 'muppet', us: 'dimwit', score: defaultScore  },
  { brit: 'mutt\'n', us: 'deaf', score: defaultScore  },
  { brit: 'nackered', us: 'tired', score: defaultScore  },
  { brit: 'naff', us: 'tacky', score: defaultScore  },
  { brit: 'nancy', us: 'homosexual', score: defaultScore  },
  { brit: 'nappies', us: 'diapers', score: defaultScore  },
  { brit: 'nappy', us: 'diaper', score: defaultScore  },
  { brit: 'narked', us: 'annoyed', score: defaultScore  },
  { brit: 'natter', us: 'chatter', score: defaultScore  },
  { brit: 'naught', us: 'zero', score: defaultScore  },
  { brit: 'naughts and crosses', us: 'tic tac toe', score: defaultScore  },
  { brit: 'navvy', us: 'road worker', score: defaultScore  },
  { brit: 'ned', us: 'white trash', score: defaultScore  },
  { brit: 'neighbour', us: 'Neighbor', score: defaultScore  },
  { brit: 'nesh', us: 'sensitive to the cold', score: defaultScore  },
  { brit: 'newsagent', us: 'newspaper vendor', score: defaultScore  },
  { brit: 'nick', us: 'steal', score: defaultScore  },
  { brit: 'nicked', us: 'busted', score: defaultScore  },
  { brit: 'nickers', us: 'underwear', score: defaultScore  },
  { brit: 'niggle', us: 'nagging problem', score: defaultScore  },
  { brit: 'niggling', us: 'nagging', score: defaultScore  },
  { brit: 'nincompoop', us: 'idiot', score: defaultScore  },
  { brit: 'ninny', us: 'idiot', score: defaultScore  },
  { brit: 'nip round the local', us: 'go to the bar', score: defaultScore  },
  { brit: 'nippy', us: 'irritating', score: defaultScore  },
  { brit: 'nithered', us: 'freezing', score: defaultScore  },
  { brit: 'nob', us: 'penis', score: defaultScore  },
  { brit: 'nobble', us: 'disable', score: defaultScore  },
  { brit: 'noice', us: 'nice', score: defaultScore  },
  { brit: 'nonce', us: 'child molestor', score: defaultScore  },
  { brit: 'norks', us: 'breasts', score: defaultScore  },
  { brit: 'norwich', us: 'nickers off ready when I come home', score: defaultScore  },
  { brit: 'nosh', us: 'snack', score: defaultScore  },
  { brit: 'nought', us: 'zero', score: defaultScore  },
  { brit: 'noughts and crosses', us: 'tic tac toe', score: defaultScore  },
  { brit: 'nout', us: 'Nothing', score: defaultScore  },
  { brit: 'nowt', us: 'nothing', score: defaultScore  },
  { brit: 'nuffink', us: 'nothing', score: defaultScore  },
  { brit: 'number plate', us: 'license plate', score: defaultScore  },
  { brit: 'numbskull', us: 'idiot', score: defaultScore  },
  { brit: 'numpty', us: 'idiot', score: defaultScore  },
  { brit: 'nutter', us: 'insane person', score: defaultScore  },
  { brit: 'Och', us: 'wow', score: defaultScore  },
  { brit: 'oestrogen', us: 'estrogen', score: defaultScore  },
  { brit: 'off license', us: 'liquor store', score: defaultScore  },
  { brit: 'offence', us: 'offense', score: defaultScore  },
  { brit: 'oggy', us: 'pasty', score: defaultScore  },
  { brit: 'oi', us: 'hey', score: defaultScore  },
  { brit: 'ol\'', us: 'Old', score: defaultScore  },
  { brit: 'old bill', us: 'police', score: defaultScore  },
  { brit: 'olde', us: 'old', score: defaultScore  },
  { brit: 'on the dole', us: 'unemployed', score: defaultScore  },
  { brit: 'on yer tod', us: 'on your own', score: defaultScore  },
  { brit: 'one off', us: 'something that happens once', score: defaultScore  },
  { brit: 'optimisation', us: 'optimization', score: defaultScore  },
  { brit: 'orf', us: 'off', score: defaultScore  },
  { brit: 'organisation', us: 'Organization', score: defaultScore  },
  { brit: 'organise', us: 'organize', score: defaultScore  },
  { brit: 'organising', us: 'Organizing', score: defaultScore  },
  { brit: 'orientated', us: 'oriented', score: defaultScore  },
  { brit: 'outskirts', us: 'suburbs', score: defaultScore  },
  { brit: 'outwith', us: 'outside', score: defaultScore  },
  { brit: 'p.a.', us: 'personal assistant', score: defaultScore  },
  { brit: 'paediatric', us: 'pediatric', score: defaultScore  },
  { brit: 'paedophile', us: 'pedophile', score: defaultScore  },
  { brit: 'pants', us: 'underwear', score: defaultScore  },
  { brit: 'parcel', us: 'Package', score: defaultScore  },
  { brit: 'parchment', us: 'Paper', score: defaultScore  },
  { brit: 'parky', us: 'chilly', score: defaultScore  },
  { brit: 'parlour', us: 'parlor', score: defaultScore  },
  { brit: 'parritch', us: 'porridge', score: defaultScore  },
  { brit: 'pastie', us: 'meat pie', score: defaultScore  },
  { brit: 'pater', us: 'father', score: defaultScore  },
  { brit: 'pavement', us: 'sidewalk', score: defaultScore  },
  { brit: 'pay packet', us: 'pay check', score: defaultScore  },
  { brit: 'pear shaped', us: 'gone wrong', score: defaultScore  },
  { brit: 'peckish', us: 'hungry', score: defaultScore  },
  { brit: 'pence', us: 'cents', score: defaultScore  },
  { brit: 'pensioner', us: 'old person', score: defaultScore  },
  { brit: 'perspex', us: 'plexiglass', score: defaultScore  },
  { brit: 'pete tong', us: 'wrong', score: defaultScore  },
  { brit: 'petrol', us: 'gas', score: defaultScore  },
  { brit: 'phone box', us: 'phone booth', score: defaultScore  },
  { brit: 'phut', us: 'expired', score: defaultScore  },
  { brit: 'pickled', us: 'drunk', score: defaultScore  },
  { brit: 'piddle', us: 'Pee', score: defaultScore  },
  { brit: 'piddled', us: 'peed', score: defaultScore  },
  { brit: 'piddles', us: 'pees', score: defaultScore  },
  { brit: 'piehole', us: 'mouth', score: defaultScore  },
  { brit: 'pikey', us: 'white trash', score: defaultScore  },
  { brit: 'pillock', us: 'idiot', score: defaultScore  },
  { brit: 'pillow biter', us: 'homosexual', score: defaultScore  },
  { brit: 'pinch', us: 'steal', score: defaultScore  },
  { brit: 'pinhead', us: 'idiot', score: defaultScore  },
  { brit: 'pinney', us: 'Apron', score: defaultScore  },
  { brit: 'pips', us: 'seeds', score: defaultScore  },
  { brit: 'pish', us: 'piss', score: defaultScore  },
  { brit: 'pished', us: 'drunk', score: defaultScore  },
  { brit: 'piss artist', us: 'drunkard', score: defaultScore  },
  { brit: 'pissed', us: 'drunk', score: defaultScore  },
  { brit: 'pisshead', us: 'drunk person', score: defaultScore  },
  { brit: 'pissy eyed', us: 'drunk', score: defaultScore  },
  { brit: 'pitch', us: 'field', score: defaultScore  },
  { brit: 'plank', us: 'idiot', score: defaultScore  },
  { brit: 'plaster', us: 'bandaid', score: defaultScore  },
  { brit: 'plastered', us: 'drunk', score: defaultScore  },
  { brit: 'plates of meat', us: 'feet', score: defaultScore  },
  { brit: 'pleb', us: 'idiot', score: defaultScore  },
  { brit: 'plod', us: 'police', score: defaultScore  },
  { brit: 'plonker', us: 'idiot', score: defaultScore  },
  { brit: 'plopper', us: 'toilet', score: defaultScore  },
  { brit: 'plough', us: 'plow', score: defaultScore  },
  { brit: 'plunker', us: 'idiot', score: defaultScore  },
  { brit: 'po faced', us: 'glum', score: defaultScore  },
  { brit: 'polo neck', us: 'turtle neck', score: defaultScore  },
  { brit: 'polythene', us: 'polyethylene', score: defaultScore  },
  { brit: 'pommy', us: 'english', score: defaultScore  },
  { brit: 'ponce', us: 'idiot', score: defaultScore  },
  { brit: 'pong', us: 'bad smell', score: defaultScore  },
  { brit: 'poo', us: 'poop', score: defaultScore  },
  { brit: 'poochie', us: 'Vagina', score: defaultScore  },
  { brit: 'poof', us: 'homosexual', score: defaultScore  },
  { brit: 'poofter', us: 'homosexual', score: defaultScore  },
  { brit: 'pop', us: 'dad', score: defaultScore  },
  { brit: 'poppet', us: 'child', score: defaultScore  },
  { brit: 'poppycock', us: 'Unbelievable', score: defaultScore  },
  { brit: 'pork sword', us: 'penis', score: defaultScore  },
  { brit: 'porkies', us: 'lies', score: defaultScore  },
  { brit: 'porky', us: 'Lie', score: defaultScore  },
  { brit: 'porky pies', us: 'lies', score: defaultScore  },
  { brit: 'porridge', us: 'oatmeal', score: defaultScore  },
  { brit: 'porter', us: 'doorman', score: defaultScore  },
  { brit: 'posh', us: 'well to do', score: defaultScore  },
  { brit: 'post', us: 'mail', score: defaultScore  },
  { brit: 'postage & packing', us: 'shipping & handling', score: defaultScore  },
  { brit: 'postbox', us: 'mailbox', score: defaultScore  },
  { brit: 'postcode', us: 'zip code', score: defaultScore  },
  { brit: 'postie', us: 'mailman', score: defaultScore  },
  { brit: 'potholing', us: 'spelunking', score: defaultScore  },
  { brit: 'potty', us: 'loopy', score: defaultScore  },
  { brit: 'practising', us: 'practicing', score: defaultScore  },
  { brit: 'pram', us: 'baby carriage', score: defaultScore  },
  { brit: 'pranged', us: 'dented', score: defaultScore  },
  { brit: 'prat', us: 'idiot', score: defaultScore  },
  { brit: 'prawn', us: 'shrimp', score: defaultScore  },
  { brit: 'press studs', us: 'snaps', score: defaultScore  },
  { brit: 'pretence', us: 'pretense', score: defaultScore  },
  { brit: 'programme', us: 'program', score: defaultScore  },
  { brit: 'pub', us: 'bar', score: defaultScore  },
  { brit: 'pudding', us: 'Dessert', score: defaultScore  },
  { brit: 'pukka', us: 'Brilliant', score: defaultScore  },
  { brit: 'punch-up', us: 'fistfight', score: defaultScore  },
  { brit: 'pushchair', us: 'stroller', score: defaultScore  },
  { brit: 'pushpin', us: 'thumbtack', score: defaultScore  },
  { brit: 'pyjamas', us: 'pajamas', score: defaultScore  },
  { brit: 'queue', us: 'line', score: defaultScore  },
  { brit: 'queueing', us: 'lining', score: defaultScore  },
  { brit: 'quid', us: 'currency', score: defaultScore  },
  { brit: 'quine', us: 'girl', score: defaultScore  },
  { brit: 'railway', us: 'railroad', score: defaultScore  },
  { brit: 'randy', us: 'horny', score: defaultScore  },
  { brit: 'ranker', us: 'enlisted man', score: defaultScore  },
  { brit: 'rasher', us: 'bacon strip', score: defaultScore  },
  { brit: 'rat arsed', us: 'drunk', score: defaultScore  },
  { brit: 'rat-arsed', us: 'drunk', score: defaultScore  },
  { brit: 'ratted', us: 'drunk', score: defaultScore  },
  { brit: 'razz', us: 'puke', score: defaultScore  },
  { brit: 'razzed', us: 'puked', score: defaultScore  },
  { brit: 'razzers', us: 'Police', score: defaultScore  },
  { brit: 'readies', us: 'folding money', score: defaultScore  },
  { brit: 'realise', us: 'realize', score: defaultScore  },
  { brit: 'recognise', us: 'recognize', score: defaultScore  },
  { brit: 'reeking green trees', us: 'Marijuana', score: defaultScore  },
  { brit: 'removal van', us: 'moving van', score: defaultScore  },
  { brit: 'restroom', us: 'staff room', score: defaultScore  },
  { brit: 'return ticket', us: 'round trip ticket', score: defaultScore  },
  { brit: 'reverse charge call', us: 'collect call', score: defaultScore  },
  { brit: 'reversing lights', us: 'back-up lights', score: defaultScore  },
  { brit: 'ring up', us: 'call', score: defaultScore  },
  { brit: 'rodger', us: 'horny', score: defaultScore  },
  { brit: 'romp', us: 'fuck', score: defaultScore  },
  { brit: 'romped', us: 'fucked', score: defaultScore  },
  { brit: 'ropey', us: 'not in good shape', score: defaultScore  },
  { brit: 'rosie', us: 'tea', score: defaultScore  },
  { brit: 'rosy lea', us: 'cup of tea', score: defaultScore  },
  { brit: 'roundabout', us: 'traffic circle', score: defaultScore  },
  { brit: 'row', us: 'argument', score: defaultScore  },
  { brit: 'rub dub', us: 'Pub', score: defaultScore  },
  { brit: 'rubber', us: 'eraser', score: defaultScore  },
  { brit: 'rubber jonny', us: 'condom', score: defaultScore  },
  { brit: 'rubbish', us: 'trash', score: defaultScore  },
  { brit: 'rucksack', us: 'backpack', score: defaultScore  },
  { brit: 'ruddy', us: 'fucking', score: defaultScore  },
  { brit: 'rumour', us: 'rumor', score: defaultScore  },
  { brit: 'sacked', us: 'fired', score: defaultScore  },
  { brit: 'saffer', us: 'South African', score: defaultScore  },
  { brit: 'saffie', us: 'South African', score: defaultScore  },
  { brit: 'salmon canyon', us: 'vagina', score: defaultScore  },
  { brit: 'samey', us: 'similar', score: defaultScore  },
  { brit: 'sarnie', us: 'sandwich', score: defaultScore  },
  { brit: 'sarnies', us: 'sandwiches', score: defaultScore  },
  { brit: 'saviour', us: 'savior', score: defaultScore  },
  { brit: 'scally', us: 'White Trash', score: defaultScore  },
  { brit: 'scallywag', us: 'rascal', score: defaultScore  },
  { brit: 'scapa', us: 'run', score: defaultScore  },
  { brit: 'scarper', us: 'run away', score: defaultScore  },
  { brit: 'scarpered', us: 'ran away', score: defaultScore  },
  { brit: 'schemie', us: 'hoodlum', score: defaultScore  },
  { brit: 'schtum', us: 'shut', score: defaultScore  },
  { brit: 'scone', us: 'biscuit', score: defaultScore  },
  { brit: 'scones', us: 'biscuits', score: defaultScore  },
  { brit: 'scouser', us: 'person from Liverpool', score: defaultScore  },
  { brit: 'scrap', us: 'junk', score: defaultScore  },
  { brit: 'scrote', us: 'scum', score: defaultScore  },
  { brit: 'scrummy', us: 'yummy', score: defaultScore  },
  { brit: 'scrumpy', us: 'nasty drink', score: defaultScore  },
  { brit: 'scuffer', us: 'policeman', score: defaultScore  },
  { brit: 'scupper', us: 'obstruct', score: defaultScore  },
  { brit: 'scuppereed', us: 'stopped', score: defaultScore  },
  { brit: 'sellotape', us: 'scotch tape', score: defaultScore  },
  { brit: 'semi housing', us: 'duplex', score: defaultScore  },
  { brit: 'seppo', us: 'Yankee', score: defaultScore  },
  { brit: 'septic', us: 'american', score: defaultScore  },
  { brit: 'septic tank', us: 'yank', score: defaultScore  },
  { brit: 'septics', us: 'americans', score: defaultScore  },
  { brit: 'settee', us: 'sofa', score: defaultScore  },
  { brit: 'shag', us: 'fuck', score: defaultScore  },
  { brit: 'shagadelic', us: 'fuckable', score: defaultScore  },
  { brit: 'shagged', us: 'fucked', score: defaultScore  },
  { brit: 'shambolic', us: 'unorganized', score: defaultScore  },
  { brit: 'shandy', us: 'beer and lemonade', score: defaultScore  },
  { brit: 'shank', us: 'knife', score: defaultScore  },
  { brit: 'shash', us: 'nonsense', score: defaultScore  },
  { brit: 'shat', us: 'took a shit', score: defaultScore  },
  { brit: 'shazza', us: 'female white trash', score: defaultScore  },
  { brit: 'shilling', us: 'money', score: defaultScore  },
  { brit: 'shirt lifter', us: 'faggott', score: defaultScore  },
  { brit: 'shirt-lifter', us: 'faggott', score: defaultScore  },
  { brit: 'shirty', us: 'irritable', score: defaultScore  },
  { brit: 'shit hot', us: 'fantastic', score: defaultScore  },
  { brit: 'shit me whack', us: 'pooed my pants', score: defaultScore  },
  { brit: 'shite', us: 'shit', score: defaultScore  },
  { brit: 'shitfaced', us: 'drunk', score: defaultScore  },
  { brit: 'shiv', us: 'stab', score: defaultScore  },
  { brit: 'shizz', us: 'shit', score: defaultScore  },
  { brit: 'shoddy', us: 'cheap', score: defaultScore  },
  { brit: 'shoney', us: 'crawl', score: defaultScore  },
  { brit: 'shopping centre', us: 'shopping mall', score: defaultScore  },
  { brit: 'shopping hall', us: 'mall', score: defaultScore  },
  { brit: 'shopping trolley', us: 'shopping cart', score: defaultScore  },
  { brit: 'shufty', us: 'look', score: defaultScore  },
  { brit: 'sixes and sevens', us: 'crazy', score: defaultScore  },
  { brit: 'skallywag', us: 'rascal', score: defaultScore  },
  { brit: 'skane', us: 'I see', score: defaultScore  },
  { brit: 'skanky', us: 'slutty', score: defaultScore  },
  { brit: 'skanky', us: 'slut', score: defaultScore  },
  { brit: 'sken', us: 'look', score: defaultScore  },
  { brit: 'sket', us: 'slut', score: defaultScore  },
  { brit: 'skids', us: 'Underwear', score: defaultScore  },
  { brit: 'skinfull', us: 'enough alcohol to get drunk', score: defaultScore  },
  { brit: 'skins', us: 'condoms', score: defaultScore  },
  { brit: 'skint', us: 'poor', score: defaultScore  },
  { brit: 'skip', us: 'trash can', score: defaultScore  },
  { brit: 'skive', us: 'unauthorized absence', score: defaultScore  },
  { brit: 'sky rocket', us: 'pocket', score: defaultScore  },
  { brit: 'skyrocket', us: 'pocket', score: defaultScore  },
  { brit: 'slag', us: 'slut', score: defaultScore  },
  { brit: 'slaggy', us: 'slutty', score: defaultScore  },
  { brit: 'slapper', us: 'desperate person', score: defaultScore  },
  { brit: 'slash', us: 'piss', score: defaultScore  },
  { brit: 'slaughtered', us: 'Drunk', score: defaultScore  },
  { brit: 'sleeping policeman', us: 'speed bump', score: defaultScore  },
  { brit: 'sleeping rough', us: 'homeless', score: defaultScore  },
  { brit: 'slewed', us: 'drunk', score: defaultScore  },
  { brit: 'slippy', us: 'slippery', score: defaultScore  },
  { brit: 'slummy', us: 'loose change', score: defaultScore  },
  { brit: 'smalls', us: 'underpants', score: defaultScore  },
  { brit: 'smarm', us: 'polite but insincere', score: defaultScore  },
  { brit: 'smarmy', us: 'polite, insincere', score: defaultScore  },
  { brit: 'smart dress', us: 'formal attire', score: defaultScore  },
  { brit: 'smashing', us: 'good', score: defaultScore  },
  { brit: 'smeg', us: 'gooey substance', score: defaultScore  },
  { brit: 'smeg-for-brains', us: 'idiot', score: defaultScore  },
  { brit: 'smeghead', us: 'idiot', score: defaultScore  },
  { brit: 'snigger', us: 'snicker', score: defaultScore  },
  { brit: 'snockered', us: 'drunk', score: defaultScore  },
  { brit: 'snog', us: 'kiss', score: defaultScore  },
  { brit: 'snogged', us: 'kissed', score: defaultScore  },
  { brit: 'snogging', us: 'kissing', score: defaultScore  },
  { brit: 'snooker', us: 'pool', score: defaultScore  },
  { brit: 'sod all', us: 'nothing', score: defaultScore  },
  { brit: 'sod it', us: 'forget it', score: defaultScore  },
  { brit: 'sod off', us: 'get lost', score: defaultScore  },
  { brit: 'sod you', us: 'bite me', score: defaultScore  },
  { brit: 'sodding', us: 'annoying', score: defaultScore  },
  { brit: 'softie', us: 'wimp', score: defaultScore  },
  { brit: 'solicitor', us: 'lawyer', score: defaultScore  },
  { brit: 'soya', us: 'soy', score: defaultScore  },
  { brit: 'spack', us: 'idiot', score: defaultScore  },
  { brit: 'spacker', us: 'idiot', score: defaultScore  },
  { brit: 'spanner', us: 'wrench', score: defaultScore  },
  { brit: 'sparky', us: 'electrician', score: defaultScore  },
  { brit: 'specs', us: 'glasses', score: defaultScore  },
  { brit: 'spiffing', us: 'excellent', score: defaultScore  },
  { brit: 'splendid', us: 'excellent', score: defaultScore  },
  { brit: 'spotted dick', us: 'sponge cake with raisins', score: defaultScore  },
  { brit: 'spotty', us: 'zit faced', score: defaultScore  },
  { brit: 'sprog', us: 'small child', score: defaultScore  },
  { brit: 'spud', us: 'potato', score: defaultScore  },
  { brit: 'spunk', us: 'semen', score: defaultScore  },
  { brit: 'squaddie', us: 'soldier', score: defaultScore  },
  { brit: 'squidgy', us: 'malleable', score: defaultScore  },
  { brit: 'squiffy', us: 'pear shaped', score: defaultScore  },
  { brit: 'squinty', us: 'crooked', score: defaultScore  },
  { brit: 'squiz', us: 'look', score: defaultScore  },
  { brit: 'stag night', us: 'bachelor party', score: defaultScore  },
  { brit: 'starkers', us: 'naked', score: defaultScore  },
  { brit: 'steady on', us: 'whoa', score: defaultScore  },
  { brit: 'steamin', us: 'drunk', score: defaultScore  },
  { brit: 'steaming', us: 'drunk', score: defaultScore  },
  { brit: 'sterling', us: 'great', score: defaultScore  },
  { brit: 'steve mcqueens', us: 'jeans', score: defaultScore  },
  { brit: 'stiff one', us: 'strong drink', score: defaultScore  },
  { brit: 'stonking', us: 'great', score: defaultScore  },
  { brit: 'straight away', us: 'right away', score: defaultScore  },
  { brit: 'stroppy', us: 'grumpy', score: defaultScore  },
  { brit: 'sulphur', us: 'sulfur', score: defaultScore  },
  { brit: 'sultanas', us: 'yellow raisins', score: defaultScore  },
  { brit: 'sumfink', us: 'something', score: defaultScore  },
  { brit: 'summat', us: 'something', score: defaultScore  },
  { brit: 'supper', us: 'dinner', score: defaultScore  },
  { brit: 'supper', us: 'dinner', score: defaultScore  },
  { brit: 'surname', us: 'last name', score: defaultScore  },
  { brit: 'suss', us: 'realise', score: defaultScore  },
  { brit: 'swamp hopper', us: 'REALLY ugly chick', score: defaultScore  },
  { brit: 'sweets', us: 'candy', score: defaultScore  },
  { brit: 'sweetshop', us: 'candy store', score: defaultScore  },
  { brit: 'swift half', us: 'quick drink', score: defaultScore  },
  { brit: 'swiftie', us: 'quick drink', score: defaultScore  },
  { brit: 'swimmers', us: 'swim trunks', score: defaultScore  },
  { brit: 'swimming costume', us: 'swimsuit', score: defaultScore  },
  { brit: 'swindle', us: 'con', score: defaultScore  },
  { brit: 'switched on', us: 'sexy', score: defaultScore  },
  { brit: 'swither', us: 'hesitate', score: defaultScore  },
  { brit: 'swizz', us: 'con', score: defaultScore  },
  { brit: 'swot', us: 'book worm', score: defaultScore  },
  { brit: 'swotting', us: 'cramming', score: defaultScore  },
  { brit: 'ta', us: 'thank you', score: defaultScore  },
  { brit: 'table football', us: 'foosball', score: defaultScore  },
  { brit: 'tackle', us: 'equiptment', score: defaultScore  },
  { brit: 'tad', us: 'bit', score: defaultScore  },
  { brit: 'tadge', us: 'penis', score: defaultScore  },
  { brit: 'tadger', us: 'penis', score: defaultScore  },
  { brit: 'tailback', us: 'traffic jam', score: defaultScore  },
  { brit: 'take away', us: 'carry out', score: defaultScore  },
  { brit: 'taking the mickey', us: 'making fun', score: defaultScore  },
  { brit: 'taking the piss', us: 'making fun', score: defaultScore  },
  { brit: 'takings', us: 'receipts', score: defaultScore  },
  { brit: 'tanked', us: 'very drunk', score: defaultScore  },
  { brit: 'tannoy', us: 'public address system', score: defaultScore  },
  { brit: 'tardy', us: 'late', score: defaultScore  },
  { brit: 'tart', us: 'homosexual', score: defaultScore  },
  { brit: 'tart fuel', us: 'cheap, often fruit flavoured, alcoholic drinks', score: defaultScore  },
  { brit: 'tartan', us: 'plaid', score: defaultScore  },
  { brit: 'tater', us: 'potato', score: defaultScore  },
  { brit: 'taters', us: 'cold', score: defaultScore  },
  { brit: 'tea break', us: 'coffee break', score: defaultScore  },
  { brit: 'tele', us: 'television', score: defaultScore  },
  { brit: 'telebox', us: 'Television', score: defaultScore  },
  { brit: 'telly', us: 'tv', score: defaultScore  },
  { brit: 'tetchy', us: 'touchy', score: defaultScore  },
  { brit: 'the baked bean', us: 'the queen', score: defaultScore  },
  { brit: 'the battlecruiser', us: 'the drinking establishment', score: defaultScore  },
  { brit: 'the beeb', us: 'the BBC', score: defaultScore  },
  { brit: 'the bollocks', us: 'the best', score: defaultScore  },
  { brit: 'the dog\'s bollocks', us: 'great', score: defaultScore  },
  { brit: 'the dogs bollocks', us: 'the best', score: defaultScore  },
  { brit: 'the ready', us: 'the spare cash', score: defaultScore  },
  { brit: 'the stink', us: 'asshole', score: defaultScore  },
  { brit: 'the tits', us: 'the best', score: defaultScore  },
  { brit: 'the tube', us: 'the subway', score: defaultScore  },
  { brit: 'theatre', us: 'theater', score: defaultScore  },
  { brit: 'thine', us: 'yours', score: defaultScore  },
  { brit: 'thingamajig', us: 'thing', score: defaultScore  },
  { brit: 'thingamijig', us: 'thing', score: defaultScore  },
  { brit: 'thou', us: 'you', score: defaultScore  },
  { brit: 'tidings', us: 'news', score: defaultScore  },
  { brit: 'tiffin', us: 'old car', score: defaultScore  },
  { brit: 'tiger nuts', us: 'dingleberries', score: defaultScore  },
  { brit: 'tilil', us: 'cash register', score: defaultScore  },
  { brit: 'till', us: 'cash register', score: defaultScore  },
  { brit: 'tinned', us: 'canned', score: defaultScore  },
  { brit: 'tippex', us: 'white out', score: defaultScore  },
  { brit: 'tipple', us: 'some sort of drink', score: defaultScore  },
  { brit: 'tipsy', us: 'drunk', score: defaultScore  },
  { brit: 'titchy', us: 'very small', score: defaultScore  },
  { brit: 'titfer', us: 'hat', score: defaultScore  },
  { brit: 'tits up', us: 'gone wrong', score: defaultScore  },
  { brit: 'to bits', us: 'very much', score: defaultScore  },
  { brit: 'toddle on off', us: 'move along to', score: defaultScore  },
  { brit: 'todge', us: 'penis', score: defaultScore  },
  { brit: 'todger', us: 'penis', score: defaultScore  },
  { brit: 'toe rag', us: 'scoundrel', score: defaultScore  },
  { brit: 'toff', us: 'upper class', score: defaultScore  },
  { brit: 'toilet', us: 'bathroom', score: defaultScore  },
  { brit: 'tolly', us: 'White Trash', score: defaultScore  },
  { brit: 'tom tit', us: 'shit', score: defaultScore  },
  { brit: 'tomato sauce', us: 'catsup', score: defaultScore  },
  { brit: 'tongue-wrestle', us: 'kiss', score: defaultScore  },
  { brit: 'tonne', us: 'ton', score: defaultScore  },
  { brit: 'toodle pip', us: 'goodbye', score: defaultScore  },
  { brit: 'toodly', us: 'brilliant', score: defaultScore  },
  { brit: 'top banana', us: 'First Rate', score: defaultScore  },
  { brit: 'top hole', us: 'finest quality', score: defaultScore  },
  { brit: 'top notch', us: 'finest quality', score: defaultScore  },
  { brit: 'torch', us: 'flashlight', score: defaultScore  },
  { brit: 'toss', us: 'masturbate', score: defaultScore  },
  { brit: 'toss-pot', us: 'jerk', score: defaultScore  },
  { brit: 'tosser', us: 'faggott', score: defaultScore  },
  { brit: 'tottie', us: 'tiny', score: defaultScore  },
  { brit: 'totty', us: 'pretty girl', score: defaultScore  },
  { brit: 'tracky', us: 'tracksuit', score: defaultScore  },
  { brit: 'trainers', us: 'sneakers', score: defaultScore  },
  { brit: 'tram', us: 'train', score: defaultScore  },
  { brit: 'tranny', us: 'radio', score: defaultScore  },
  { brit: 'treacle', us: 'molasses', score: defaultScore  },
  { brit: 'trilby', us: 'felt hat', score: defaultScore  },
  { brit: 'trolley', us: 'shopping cart', score: defaultScore  },
  { brit: 'trolley dolly', us: 'stewardess', score: defaultScore  },
  { brit: 'trolleyed', us: 'drunk', score: defaultScore  },
  { brit: 'trollop', us: 'slut', score: defaultScore  },
  { brit: 'trouble and strife', us: 'wife', score: defaultScore  },
  { brit: 'trouser snake', us: 'dick', score: defaultScore  },
  { brit: 'trousers', us: 'pants', score: defaultScore  },
  { brit: 'tube', us: 'subway', score: defaultScore  },
  { brit: 'tugger', us: 'Jerk off', score: defaultScore  },
  { brit: 'tumour', us: 'tumor', score: defaultScore  },
  { brit: 'tumped', us: 'farted', score: defaultScore  },
  { brit: 'twat', us: 'pussy', score: defaultScore  },
  { brit: 'twatted', us: 'hit', score: defaultScore  },
  { brit: 'twee', us: 'tacky', score: defaultScore  },
  { brit: 'twig', us: 'catch on', score: defaultScore  },
  { brit: 'twit', us: 'nitwit', score: defaultScore  },
  { brit: 'twonk', us: 'idiot', score: defaultScore  },
  { brit: 'tyre', us: 'tire', score: defaultScore  },
  { brit: 'tyres', us: 'tires', score: defaultScore  },
  { brit: 'uncle ned', us: 'bed', score: defaultScore  },
  { brit: 'unit trust', us: 'mutual fund', score: defaultScore  },
  { brit: 'up the duff', us: 'pregnant', score: defaultScore  },
  { brit: 'up the spout', us: 'not working', score: defaultScore  },
  { brit: 'uphill gardener', us: 'homosexual', score: defaultScore  },
  { brit: 'vapour', us: 'vapor', score: defaultScore  },
  { brit: 'veras', us: 'cigarette papers', score: defaultScore  },
  { brit: 'waffle', us: 'rambling conversation', score: defaultScore  },
  { brit: 'waistcoat', us: 'vest', score: defaultScore  },
  { brit: 'wally', us: 'idiot', score: defaultScore  },
  { brit: 'wank', us: 'masturbate', score: defaultScore  },
  { brit: 'wanked', us: 'jerked', score: defaultScore  },
  { brit: 'wanker', us: 'jerk off', score: defaultScore  },
  { brit: 'wankered', us: 'drunk', score: defaultScore  },
  { brit: 'wankers', us: 'jerk offs', score: defaultScore  },
  { brit: 'wanking', us: 'masturbating', score: defaultScore  },
  { brit: 'wanking chariot', us: 'bed', score: defaultScore  },
  { brit: 'wanking off', us: 'Masterbating', score: defaultScore  },
  { brit: 'waps', us: 'breasts', score: defaultScore  },
  { brit: 'wardrobe', us: 'Closet', score: defaultScore  },
  { brit: 'washing-up liquid', us: 'dish soap', score: defaultScore  },
  { brit: 'wassak', us: 'idiot', score: defaultScore  },
  { brit: 'water biscuit', us: 'soda cracker', score: defaultScore  },
  { brit: 'water closet', us: 'bathroom', score: defaultScore  },
  { brit: 'wazz', us: 'piss', score: defaultScore  },
  { brit: 'wazzack', us: 'idiot', score: defaultScore  },
  { brit: 'wazzak', us: 'idiot', score: defaultScore  },
  { brit: 'wazzock', us: 'idiot', score: defaultScore  },
  { brit: 'wc', us: 'bathroom', score: defaultScore  },
  { brit: 'wean', us: 'child', score: defaultScore  },
  { brit: 'wedge', us: 'money', score: defaultScore  },
  { brit: 'wee', us: 'small', score: defaultScore  },
  { brit: 'wellies', us: 'boots', score: defaultScore  },
  { brit: 'wellingtons', us: 'boots', score: defaultScore  },
  { brit: 'welly', us: 'boot', score: defaultScore  },
  { brit: 'whazzock', us: 'idiot', score: defaultScore  },
  { brit: 'wheelie bin', us: 'trashcan', score: defaultScore  },
  { brit: 'whilst', us: 'while', score: defaultScore  },
  { brit: 'whimpy bar', us: 'hamburger stand', score: defaultScore  },
  { brit: 'whinge', us: 'whine', score: defaultScore  },
  { brit: 'whinger', us: 'whiner', score: defaultScore  },
  { brit: 'whinging', us: 'Whining', score: defaultScore  },
  { brit: 'whip round', us: 'collection of money', score: defaultScore  },
  { brit: 'whispering eye', us: 'Vagina', score: defaultScore  },
  { brit: 'whistle and flute', us: 'suit', score: defaultScore  },
  { brit: 'whoops a daisy', us: 'oops', score: defaultScore  },
  { brit: 'widdershins', us: 'Clockwise', score: defaultScore  },
  { brit: 'wifey queer', us: 'lesbian', score: defaultScore  },
  { brit: 'willie', us: 'penis', score: defaultScore  },
  { brit: 'willy', us: 'penis', score: defaultScore  },
  { brit: 'windscreen', us: 'windshield', score: defaultScore  },
  { brit: 'wing mirrors', us: 'side mirrors', score: defaultScore  },
  { brit: 'wintry', us: 'Cheerless, cold', score: defaultScore  },
  { brit: 'wonga', us: 'money', score: defaultScore  },
  { brit: 'wonky', us: 'not quite right', score: defaultScore  },
  { brit: 'wotcha', us: 'hi', score: defaultScore  },
  { brit: 'wotcher', us: 'hello', score: defaultScore  },
  { brit: 'wuzzock', us: 'idiot', score: defaultScore  },
  { brit: 'y fronts', us: 'tighty whities', score: defaultScore  },
  { brit: 'y\'r', us: 'your', score: defaultScore  },
  { brit: 'yakking', us: 'talking', score: defaultScore  },
  { brit: 'yampy', us: 'Crazy', score: defaultScore  },
  { brit: 'yank', us: 'american', score: defaultScore  },
  { brit: 'yankee', us: 'American', score: defaultScore  },
  { brit: 'yanks', us: 'Americans', score: defaultScore  },
  { brit: 'yardie', us: 'mobster', score: defaultScore  },
  { brit: 'ye', us: 'you', score: defaultScore  },
  { brit: 'yeh', us: 'you', score: defaultScore  },
  { brit: 'yer', us: 'your', score: defaultScore  },
  { brit: 'yob', us: 'hooligan', score: defaultScore  },
  { brit: 'yobbo', us: 'hooligan', score: defaultScore  },
  { brit: 'yobs', us: 'boys', score: defaultScore  },
  { brit: 'yonks', us: 'a long time', score: defaultScore  },
  { brit: 'zebra crossing', us: 'pedestrian crossing', score: defaultScore  },
  { brit: 'zed', us: 'z', score: defaultScore  },
  { brit: 'zimmer', us: 'walker', score: defaultScore  },
  { brit: 'zip-fastener', us: 'zipper' }
];
    
const populateQuestions = () => {
  console.log('starting... total questions = ', questions.length);
  return dbConnect()
    .then(()=>{
      return runServer();
    })
    .then(() => {
      return Questions.remove({});
    }) 
    .then(() => {
      console.log('removed');
      let batchSize = 60;  
      const unsortedQuestions = [];  
      let theQuestion; 
      for (let i = 0; i<batchSize ; i++ > 0){
        for ( let j = i; j<questions.length; j += batchSize){
          theQuestion = questions[j];
          theQuestion.nextIndex = (unsortedQuestions.length + 1);
          unsortedQuestions.push(theQuestion);
        }
      }
      unsortedQuestions[unsortedQuestions.length-1].nextIndex = null;
      return unsortedQuestions;
    })
    .then(unsortedQuestions => {
      return Questions.insertMany(unsortedQuestions);
    })
    .then(()=>{
      return closeServer();        
    });
};

// UNCOMMENT TO USE; COMMENTED FOR SAFEGUARD!
// populateQuestions();
